apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobsf
  namespace: mobsf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobsf
  template:
    metadata:
      labels:
        app: mobsf
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: mobsf
        image: opensecurity/mobile-security-framework-mobsf:latest
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1"
          limits:
            memory: "2000Mi"
            cpu: "2"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: mobsf
  namespace: mobsf
spec:
  type: NodePort
  selector:
    app: mobsf
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008  # Expose on NodePort 30008
